# Generated by Django 4.1.3 on 2023-05-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('incubator', models.CharField(choices=[('nicu_1', 'Incubator 1'), ('nicu_2', 'Incubator 2'), ('nicu_3', 'Incubator 3'), ('nicu_4', 'Incubator 4'), ('nicu_5', 'Incubator 5')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
