# Generated by Django 4.1.3 on 2023-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubator',
            name='gardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incubator',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
