# Generated by Django 4.1.3 on 2023-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('anemia_name', models.IntegerField()),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CareRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numebr_of_days', models.IntegerField()),
                ('patient_status', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('available_room', models.CharField(max_length=100)),
                ('care_room_type', models.CharField(choices=[('normal', 'Normal'), ('intensive', 'Intensive')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CentralCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('available_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('appointment_time_from', models.TimeField()),
                ('appointment_time_to', models.TimeField()),
                ('number_of_patients', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('clinic', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('medical_note', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('available_room', models.CharField(max_length=100)),
                ('child_id', models.CharField(max_length=100)),
                ('child_status', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('day_from', models.CharField(max_length=100)),
                ('day_to', models.CharField(max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_room', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('clinic', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('surgical_description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
