# Generated by Django 4.1.3 on 2022-11-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('medical_history', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('anemia_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CareRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_status', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('available_room', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('intensive', 'Intensive')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NurseryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('medical_note', models.CharField(max_length=1000)),
                ('capacity', models.IntegerField()),
                ('child_name', models.CharField(max_length=100)),
                ('available_surgircal', models.CharField(max_length=100)),
                ('busy_room', models.CharField(max_length=100)),
                ('child_id', models.CharField(max_length=100)),
                ('child_status', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('medical_history', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('day', models.CharField(max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('clinic', models.CharField(max_length=100)),
                ('surgical_description', models.CharField(max_length=1000)),
                ('doctor_name', models.CharField(max_length=100)),
                ('available_room', models.CharField(max_length=100)),
                ('patient_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppiontment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_firstname', models.CharField(max_length=100)),
                ('patient_middlename', models.CharField(max_length=100)),
                ('patient_lastname', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('clinics', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_bank', to='api.bloodbank')),
                ('nursery_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nursery_appointment', to='api.nurseryappointment')),
                ('surgical_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='surgical_appointment', to='api.surgicalappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('examination_price', models.IntegerField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('day', models.CharField(max_length=100)),
                ('care_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.careroom')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_clinic', to='api.clinic')),
                ('nursery_appiontment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nursery_appiontment', to='api.nurseryappointment')),
                ('patient_appiontment', models.ManyToManyField(blank=True, related_name='patient_appiontment', to='api.patientappiontment')),
            ],
        ),
        migrations.CreateModel(
            name='CentralCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('patient_appiontment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='central_care_appiontment', to='api.patientappiontment')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('nursery_price', models.IntegerField()),
                ('surgical_price', models.IntegerField()),
                ('doctor_price', models.IntegerField()),
                ('central_care_price', models.IntegerField()),
                ('care_room_price', models.IntegerField()),
                ('patient_appiontment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appiontment', to='api.patientappiontment')),
            ],
        ),
    ]
