# Generated by Django 4.1.3 on 2023-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicaloperation',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='api.doctor'),
        ),
    ]
