# Generated by Django 4.1.3 on 2023-01-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_surgicaloperation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_doctor', to='api.doctor'),
            preserve_default=False,
        ),
    ]
