# Generated by Django 4.1.3 on 2023-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clinic_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicaloperation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='blood_bank_doctor', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='api.doctor'),
        ),
    ]
