# Generated by Django 4.1.3 on 2023-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_surgicaloperation_doctor_bloodbank_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careroom',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='care_room_doctor', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='careroom',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='care_room_patient', to='api.patient'),
        ),
    ]
