# Generated by Django 4.1.3 on 2023-01-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_careroom_doctors_careroom_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patient_doctor', through='api.CareRoom', to='api.doctor'),
        ),
        migrations.RemoveField(
            model_name='careroom',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='careroom',
            name='patients',
        ),
        migrations.AddField(
            model_name='careroom',
            name='doctors',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='care_room_doctor', to='api.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careroom',
            name='patients',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='care_room_patient', to='api.patient'),
            preserve_default=False,
        ),
    ]
