# Generated by Django 4.1.3 on 2023-01-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_doctors_remove_careroom_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_doctor', to='api.doctor'),
            preserve_default=False,
        ),
    ]
