# Generated by Django 4.1.3 on 2023-01-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_schedule_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='nursery_doctor', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='nursery',
            name='patient',
            field=models.ManyToManyField(blank=True, related_name='nursery_patient', to='api.patient'),
        ),
    ]
