# Generated by Django 4.1.3 on 2023-01-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nursery_doctor_nursery_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralcare',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='central_care_patient', to='api.patient'),
            preserve_default=False,
        ),
    ]
