# Generated by Django 4.1.3 on 2023-02-13 00:05

from django.db import migrations, models
import django.db.models.deletion
import surgery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_remove_patient_email'),
        ('doctor', '0003_alter_speciality_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Surgery Type',
                'verbose_name_plural': 'Surgery Types',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('OR_1', 'Operation Room 1'), ('OR_2', 'Operation Room 2'), ('OR_3', 'Operation Room 3')], max_length=100)),
                ('start_time', models.DateTimeField(validators=[surgery.models.validate_start_time_end_time])),
                ('end_time', models.DateTimeField(validators=[surgery.models.validate_start_time_end_time])),
                ('doctors', models.ManyToManyField(to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgerytype')),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
            },
        ),
    ]
