# Generated by Django 4.1.3 on 2023-05-24 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('OR_1', 'Operation Room 1'), ('OR_2', 'Operation Room 2'), ('OR_3', 'Operation Room 3')], max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('surgery_type', models.CharField(choices=[('1', 'Heart Surgery'), ('2', 'Brain Surgery'), ('3', 'Cancer Surgery'), ('4', 'Lung Surgery'), ('5', 'Other')], default='5', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctors', models.ManyToManyField(to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
            },
        ),
    ]
