# Generated by Django 4.1.3 on 2023-02-16 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='estimated_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(choices=[('1', 'Heart Surgery'), ('2', 'Brain Surgery'), ('3', 'Cancer Surgery'), ('4', 'Lung Surgery'), ('5', 'Other')], default='5', max_length=100),
        ),
    ]
