# Generated by Django 4.1.3 on 2023-02-16 19:59

from django.db import migrations, models
import surgery.models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0002_surgery_estimated_time_surgery_surgery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='end_time',
            field=models.DateTimeField(default=None, validators=[surgery.models.validate_start_time_end_time]),
        ),
    ]
