# Generated by Django 4.1.3 on 2023-02-16 19:59

from django.db import migrations, models
import surgery.models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0003_alter_surgery_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
