# Generated by Django 4.1.3 on 2023-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0004_alter_surgery_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
