# Generated by Django 4.1.3 on 2023-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0005_alter_surgery_end_time_alter_surgery_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
