# Generated by Django 4.1.3 on 2023-02-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_speciality_doctor_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
    ]
