# Generated by Django 4.1.3 on 2023-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_speciality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='association_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
