# Generated by Django 4.1.3 on 2023-02-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_remove_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensiveCareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(choices=[('bed_1', 'Bed 1'), ('bed_2', 'Bed 2'), ('bed_3', 'Bed 3'), ('bed_4', 'Bed 4'), ('bed_5', 'Bed 5')], max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('estimated_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
