# Generated by Django 4.1.3 on 2023-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensivecareunit',
            name='estimated_time',
            field=models.DurationField(),
        ),
    ]
