# Generated by Django 4.1.3 on 2023-02-19 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0002_alter_intensivecareunit_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensivecareunit',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='intensivecareunit',
            name='estimated_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=28800), null=True),
        ),
    ]
