# Generated by Django 4.1.3 on 2023-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodbankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bloodbank',
            old_name='donated_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='patient',
        ),
    ]
